name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout code
        uses: actions/checkout@v4
=======
      - name: Checkout Repository
        uses: actions/checkout@v3
>>>>>>> ad18e213 (Added ./git-auto.sh and tracked staged other files)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

<<<<<<< HEAD
      - name: Install backend dependencies
=======
      - name: Install Backend Dependencies
        working-directory: backend
>>>>>>> ad18e213 (Added ./git-auto.sh and tracked staged other files)
        run: |
          cd backend
          pip install -r requirements.txt

<<<<<<< HEAD
=======
      - name: Run Backend Tests
        working-directory: backend
        run: |
          pytest --maxfail=1 --disable-warnings -q

>>>>>>> ad18e213 (Added ./git-auto.sh and tracked staged other files)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

<<<<<<< HEAD
      - name: Build frontend
=======
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Build Docker Image
>>>>>>> ad18e213 (Added ./git-auto.sh and tracked staged other files)
        run: |
          cd Frontend
          npm install
          CI=false npm run build
