name: Hate Speech Recognition - CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Python for backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run backend tests (Django/Flask)
      - name: Run Backend Tests
        working-directory: backend
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Step 5: Setup Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 6: Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      # Step 7: Build frontend
      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      # Step 8: Build Docker Image (Optional for now)
      - name: Build Docker Image
        run: |
          docker build -t hate-speech-app:latest .

